[config]
enable_webhooks = true
webhook_address = "https://10.10.10.93:8123/api/webhook/tXpVcw2Cc6BG2stM6xa7kycauFGljuiL"
zip_types = [ ".tar.gz", ".bz2", ".zip" ] # Does Nothing Yet 
verbose = false

[vars]
DATA_DIR = "/Users/hayden/Projects/quick-zip-cli/data"

[defaults]
name = "ENTRY"
source = ""
destination = "/backups"
clean_up = false
clean_up_source = false
keep = 1
audit = true
oldest = 4

[[jobs]]
name = "Dev Backup"
source = [
  "${DATA_DIR}/src/test_data",
]
destination = "${DATA_DIR}/dest"
clean_up = true
clean_up_source = true

[[jobs]]
name = "Dev Backup 2"
source = [
  "${DATA_DIR}/src/test_data",
]
destination = "${DATA_DIR}/dest"
clean_up = true
clean_up_source = true

[[jobs]]
name = "Dev Backup 3"
source = [
  "${DATA_DIR}/src/test_data",
]
destination = "${DATA_DIR}/dest"
clean_up = true
clean_up_source = true


