site_name: hay-kot | QuickZip
repo_url: https://github.com/hay-kot/quick-zip-cli
repo_name: hay-kot/quick-zip-cli

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("quick_zip")

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
    logo: fontawesome/regular/folder-open
  features:
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - codehilite
  - extra
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/hay-kot/wiki

extra_css:
  - "css/termynal.css"
  - "css/custom.css"

extra_javascript:
  - "js/termynal.js"
  - "js/custom.js"
nav:
  - Getting Started:
      - About: "index.md"
      - Quick Start: "getting-started/quick-start.md"
      - Usage Examples: "getting-started/usage-examples.md"
      - Config File: "getting-started/configuration-file.md"
      - Changelog: "getting-started/changelog.md"
  - Code:
      - AppConfig: "code/app-config.md"
      - BackupJob: "code/backup-job.md"
