[config]
enable_webhooks = false
webhook_address = "https://webhooks.com/webhook"
zip_types = [ ".tar.gz", ".bz2", ".zip" ] # Does Nothing Yet 
verbose = false

[vars]
DATA_DIR = "/Users/hayden/Projects/quick-zip-cli/data"

[defaults]
destination = "/backups"
clean_up = false
keep = 1
audit = true
oldest = 4

[[jobs]]
name = "Dev Backup"
source = [
  "${DATA_DIR}/src/test_data",
]
destination = "${DATA_DIR}/dest"
clean_up = true

[[jobs]]
name = "Dev Backup 2"
source = [
  "${DATA_DIR}/src/test_data",
]
destination = "${DATA_DIR}/dest"
clean_up = true

[[jobs]]
name = "Dev Backup 3"
source = [
  "${DATA_DIR}/src/test_data",
]
destination = "${DATA_DIR}/dest"
clean_up = true


